export { default as NavBar } from './components/NavBar';
export { default as DashboardSidebar } from './components/DashboardSidebar';

export { default as LandingPage } from './pages/LandingPage';
export { default as LoginPage } from './pages/LoginPage';
export { default as SignupPage } from './pages/SignupPage';
export { default as DashboardPage } from './pages/DashboardPage';
export { default as PredictPage } from './pages/PredictPage';
export { default as ResultPage } from './pages/ResultPage';
export { default as HistoryPage } from './pages/HistoryPage';
export { default as HealthProfilePage } from './pages/HealthProfilePage';
export { default as HealthTipsPage } from './pages/HealthTipsPage';
export { default as PharmacyLocatorPage } from './pages/PharmacyLocatorPage';
export { default as SpecialistFinderPage } from './pages/SpecialistFinderPage';
export { default as LabUploadPage } from './pages/LabUploadPage';
export { default as LabAnalysisPage } from './pages/LabAnalysisPage';
export { default as RemindersPage } from './pages/RemindersPage';
export { default as NotificationsPage } from './pages/NotificationsPage';
export { default as EmergencySosPage } from './pages/EmergencySosPage';
